base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"
user_name: ""
repo_name: "DailyPaper"
max_results: 2


# file paths
download_papers_path: './papers'
papers_metadata_path: 'papers_metadata.jsonl'


# categories to search
# 列表之间用AND连接，列表内每个词用OR连接
categories:
    - cs.SE # software engineering
    - cs.AI

#论文的分类
topic:
    Requirements & Design:
        - Elicitation
        - Analysis
        - Specification & Validation
        - Management

    Coding Assistant:
        - Code Pre-Training
        - Code Instruction-Tuning
        - Code Alignment
        - Code Prompting
        - Code Completion
        - Code Summarization
        - Code Editing
        - Code Translation
        - Code Reasoning
        - Code Retrieval
        - Code Understanding
        - Code Performance Optimization
        - Code Representation Learning

    Software Testing:
        - Test Generation
        - Assertion generation
        - GUI test
        - Testing automation
        - Testing prediction
        - Testing Repair

    AIOps:
        - Log Statement Generation
        - Log Parsing

    Maintenance:
        - Code Review
        - Clone Detection
        - Refactoring

    Quality Management:
        - Defect Prediction
        - Bug Localization
        - Bug Repair
        - Vulnerability Detection
        - Vulnerability Repair

    Version Control & Collaboration:
        - Git VCS

tags:
    - Code Simulation
    - Code Agents
    - Interactive Coding
    - Frontend Navigation
    - Low-Resource Language
    - Low-Level Language
    - Domain-Specific Language
    - Code RAG
    - Code Ranking
    - Program Repair
    - Type Prediction
    - Repository-Level Coding
    - Issue Resolution
    - Automated Machine Learning
    - Text-To-SQL
    - Program Proof
    - Mutation Testing
    - Fuzz Testing
    - Malicious Code Detection
    - Compiler Optimization
    - Binary Analysis and Decompilation
    - Commit Message Generation
    - Software Configuration
    - Software Modeling
    - Security and Vulnerabilities
    - Correctness
    - Hallucination
    - Efficiency
    - Robustness
    - Interpretability
    - API Usage
    - Privacy
    - Bias
    - Contamination
    - AI-Generated Code Detection
    - Human-LLM Interaction


